name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Print Python version and run script
        run: |
          python --version
          python hello_world.py
